### ISSUE TITLE
Crashing on Inject

### ISSUE THREAD

**Issue by 6ooo** [PancakeWithPotato/banana-shooter-cheat#12]
I just want to let u know, that its crashing after injecting it

**Comment by PancakeWithPotato** [comment]
I'm going to take a look at it, once i finish my finals, which is on Monday.

**Comment by 6ooo** [comment]
> I'm going to take a look at it, once i finish my finals, which is on Monday.

Alright, it hooks all functions but than ends up crashing after console appears

**Comment by PancakeWithPotato** [comment]
I looked at it, and for me it doesn't crash, loads just fine. Are you building the DLL yourself, or using the released one? Are you building Debug or Release?

**Comment by res47** [comment]
> I looked at it, and for me it doesn't crash, loads just fine. Are you building the DLL yourself, or using the released one? Are you building Debug or Release?


Its not crashing anymore, but now if i inject it, my guns just shoot insanly fast so basically every enemy is one hit which makes my game crash after few seconds. Also is aimbot already working or is it just implented as a future feature.

**Comment by PancakeWithPotato** [comment]
With the current build, the crashes with "getTransformposition" have been fixed. The aimbot also does work, with both hittargets and ammo types.

**Comment by retarded-person** [comment]
lol

**Comment by PancakeWithPotato** [comment]
wdym lol
