### ISSUE TITLE
why is this its own function

### ISSUE THREAD

**Issue by retarded-person-chromebook** [PancakeWithPotato/banana-shooter-cheat#18]
https://github.com/PancakeWithPotato/banana-shooter-cheat/blob/41a72254353b5cd06ded16e8bc83a3d648fae6e8/banana%20shooter%20cheat/core/combat/combat.cpp#L64

**Comment by retarded-person-chromebook** [comment]
it's literally a one liner you don't need to do anything else in this function no?

**Comment by PancakeWithPotato** [comment]
stfu im playing CMS

**Comment by retarded-person-chromebook** [comment]
smd loser stop making one liners functions
