### ISSUE TITLE
Weird Wallhack bug

### ISSUE THREAD

**Issue by DXXNS** [PancakeWithPotato/banana-shooter-cheat#19]
Everytime i enable the wallhack function it displays me this:
![image](https://user-images.githubusercontent.com/108888172/219876152-9d1e73fc-bf76-4543-889f-ef6ff2a64d59.png)
And the text is bugging too

**Comment by PancakeWithPotato** [comment]
cuz it isnt added

**Comment by DXXNS** [comment]
Ohhhhh
